name: norm

on : [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install
      run: python3 -m pip install -U norminette
    - name: norm
      run: norminette